# Generated by Django 3.0.5 on 2020-04-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
