# Generated by Django 3.0.5 on 2020-04-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200424_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
