# Generated by Django 3.0.5 on 2020-05-02 14:40

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200502_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
