# Generated by Django 3.0.5 on 2020-05-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
