# Generated by Django 2.2.12 on 2020-05-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20200502_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='آیا نظر فعال است'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='آیا نظر پاک شود'),
        ),
    ]
