# Generated by Django 3.0.5 on 2020-05-02 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_is_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='تام')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='ایمیل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر کاربری')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل کاربری',
                'verbose_name_plural': 'پروفایل ها',
                'ordering': ('-created_date',),
            },
        ),
    ]
