# Generated by Django 2.2.12 on 2020-05-07 10:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات فوتر')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فوتر',
                'verbose_name_plural': 'فوتر',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworksLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('yt', 'Youtube'), ('tw', 'Twitter'), ('gp', 'GooglePlus'), ('tl', 'Telegram'), ('fb', 'Facebook')], max_length=2, verbose_name='نام')),
                ('url', models.URLField(verbose_name='آدرس')),
            ],
        ),
    ]
