# Generated by Django 2.2.12 on 2020-05-07 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_contanctinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contanctinfo',
            name='footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='footer.Footer'),
        ),
        migrations.AddField(
            model_name='socialnetworkslink',
            name='footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socials', to='footer.Footer'),
        ),
    ]
