# Generated by Django 2.2.12 on 2020-05-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0003_auto_20200507_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworkslink',
            name='name',
            field=models.CharField(choices=[('yt', 'Youtube'), ('tw', 'Twitter'), ('gp', 'GooglePlus'), ('tl', 'Telegram'), ('fb', 'Facebook'), ('li', 'LinkedIn'), ('in', 'Instagram')], max_length=2, verbose_name='نام'),
        ),
    ]
