# Generated by Django 2.2.12 on 2020-05-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='majid@majid.com', max_length=254, verbose_name='ایمیل'),
            preserve_default=False,
        ),
    ]
