# Generated by Django 2.2.12 on 2020-05-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='telepone',
            new_name='telephone',
        ),
    ]
