# Generated by Django 2.2.12 on 2020-05-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
